/* themes.js — Datos temáticos de las 48 selecciones del Mundial 2026.
 * c1 = color dominante, c2 = secundario, c3 = acento.
 * code = ISO alpha-2 (para autodetección por país).
 * Los nombres (clave) coinciden EXACTO con los de TheSportsDB.
 */

const NEUTRAL = {
  short: "Mundial 2026",
  es: "Mundial 2026",
  flag: "🏆",
  nick: "La fiesta del fútbol mundial",
  confed: "FIFA · USA · Canadá · México",
  code: "",
  c1: "#0EA5E9",
  c2: "#22C55E",
  c3: "#F59E0B",
  titles: "48 selecciones · 104 partidos · 16 sedes",
  facts: [
    "Es el primer Mundial con 48 selecciones y 104 partidos, el más grande de la historia.",
    "Se juega en 3 países: Estados Unidos, Canadá y México, en 16 ciudades sede.",
    "México se convierte en el primer país en albergar partidos de Copa del Mundo en tres ediciones distintas.",
    "El estadio MetLife (Nueva Jersey) será sede de la gran final el 19 de julio de 2026.",
  ],
};

const TEAMS = {
  Argentina: { es: "Argentina", flag: "🇦🇷", code: "AR", confed: "CONMEBOL", nick: "La Albiceleste", c1: "#6CB4E4", c2: "#FFFFFF", c3: "#F6B40E", titles: "3 Mundiales · 1978, 1986, 2022", facts: ["Llega como campeona defensora tras ganar Qatar 2022 ante Francia por penales.", "Lionel Messi es el jugador con más partidos en la historia de los Mundiales.", "El himno 'Muchachos' fue la banda sonora de la consagración en 2022."] },
  Brazil: { es: "Brasil", flag: "🇧🇷", code: "BR", confed: "CONMEBOL", nick: "A Seleção / Verdeamarela", c1: "#FFDF00", c2: "#009739", c3: "#002776", titles: "5 Mundiales · récord absoluto", facts: ["Es la única selección que jugó TODAS las Copas del Mundo de la historia.", "Pelé es el único futbolista que ganó tres Mundiales (1958, 1962 y 1970).", "Su quinta estrella la consiguió en 2002 con Ronaldo como goleador."] },
  France: { es: "Francia", flag: "🇫🇷", code: "FR", confed: "UEFA", nick: "Les Bleus", c1: "#0055A4", c2: "#FFFFFF", c3: "#EF4135", titles: "2 Mundiales · 1998, 2018", facts: ["Fue finalista en 2022 y subcampeona tras un partidazo ante Argentina.", "Kylian Mbappé hizo un triplete en la final de 2022, algo que solo logró Geoff Hurst (1966).", "Ganó su primer título en casa en 1998 con Zidane como figura."] },
  Spain: { es: "España", flag: "🇪🇸", code: "ES", confed: "UEFA", nick: "La Roja", c1: "#C60B1E", c2: "#FFC400", c3: "#AD1519", titles: "1 Mundial · 2010", facts: ["Campeona del mundo en 2010 con un gol de Iniesta en la final ante Países Bajos.", "Viene de ganar la Eurocopa 2024 con un fútbol vertiginoso y joven.", "Lamine Yamal irrumpió como una de las grandes joyas del fútbol mundial."] },
  Germany: { es: "Alemania", flag: "🇩🇪", code: "DE", confed: "UEFA", nick: "Die Mannschaft", c1: "#000000", c2: "#DD0000", c3: "#FFCE00", titles: "4 Mundiales · 1954, 1974, 1990, 2014", facts: ["Su última estrella fue en Brasil 2014 con el histórico 7-1 a la anfitriona en semis.", "Miroslav Klose es el máximo goleador histórico de los Mundiales con 16 goles.", "Es la selección con más finales disputadas junto a Brasil."] },
  England: { es: "Inglaterra", flag: "🏴", code: "GB", confed: "UEFA", nick: "The Three Lions", c1: "#FFFFFF", c2: "#CF081F", c3: "#1D3D8F", titles: "1 Mundial · 1966", facts: ["Su único título fue en casa en 1966 con el recordado 'gol fantasma' de Hurst.", "Harry Kane es el máximo goleador histórico de la selección inglesa.", "Llega tras dos finales de Eurocopa perdidas (2021 y 2024) buscando revancha."] },
  Portugal: { es: "Portugal", flag: "🇵🇹", code: "PT", confed: "UEFA", nick: "A Seleção das Quinas", c1: "#006600", c2: "#FF0000", c3: "#FFD700", titles: "Mejor: 3.° en 1966", facts: ["Cristiano Ronaldo es el máximo goleador de selecciones de la historia.", "Ganó la Eurocopa 2016 y la Nations League 2019 y 2025.", "Tiene una de las generaciones más talentosas con Bruno, Leão y Bernardo Silva."] },
  Netherlands: { es: "Países Bajos", flag: "🇳🇱", code: "NL", confed: "UEFA", nick: "Oranje", c1: "#FF6200", c2: "#21468B", c3: "#AE1C28", titles: "3 finales · subcampeón 1974, 1978, 2010", facts: ["Inventores del 'fútbol total' con Johan Cruyff en los años 70.", "Es la mejor selección que nunca ganó un Mundial, con tres finales perdidas.", "Su marea naranja es una de las hinchadas más vistosas del torneo."] },
  Croatia: { es: "Croacia", flag: "🇭🇷", code: "HR", confed: "UEFA", nick: "Vatreni (Los Ardientes)", c1: "#FF0000", c2: "#FFFFFF", c3: "#171796", titles: "Subcampeón 2018 · 3.° en 2022", facts: ["Con apenas 4 millones de habitantes llegó a la final en 2018.", "Luka Modrić ganó el Balón de Oro 2018 cortando el reinado de Messi y Cristiano.", "Su camiseta a cuadros rojos y blancos es de las más reconocibles del mundo."] },
  Belgium: { es: "Bélgica", flag: "🇧🇪", code: "BE", confed: "UEFA", nick: "Los Diablos Rojos", c1: "#E30613", c2: "#000000", c3: "#FDDA24", titles: "Mejor: 3.° en 2018", facts: ["Su 'generación dorada' (De Bruyne, Hazard, Lukaku) alcanzó el podio en 2018.", "Fue número 1 del ranking FIFA durante varios años seguidos.", "Romelu Lukaku es su máximo goleador histórico."] },
  Uruguay: { es: "Uruguay", flag: "🇺🇾", code: "UY", confed: "CONMEBOL", nick: "La Celeste", c1: "#5CBFEB", c2: "#FFFFFF", c3: "#FCD116", titles: "2 Mundiales · 1930, 1950", facts: ["Ganó el primer Mundial de la historia, en casa, en 1930.", "El 'Maracanazo' de 1950 es una de las mayores hazañas del fútbol.", "Sus 4 estrellas incluyen los oros olímpicos de 1924 y 1928, reconocidos por FIFA."] },
  Colombia: { es: "Colombia", flag: "🇨🇴", code: "CO", confed: "CONMEBOL", nick: "Los Cafeteros", c1: "#FCD116", c2: "#003893", c3: "#CE1126", titles: "Mejor: cuartos en 2014", facts: ["James Rodríguez fue el goleador del Mundial 2014 con un golazo inolvidable ante Uruguay.", "Llega tras ser finalista de la Copa América 2024.", "La hinchada cafetera es famosa por su alegría y su música."] },
  Ecuador: { es: "Ecuador", flag: "🇪🇨", code: "EC", confed: "CONMEBOL", nick: "La Tri", c1: "#FFD100", c2: "#0072CE", c3: "#EF3340", titles: "Mejor: octavos en 2006", facts: ["Una de las defensas más sólidas de las Eliminatorias sudamericanas.", "Enner Valencia es su máximo goleador histórico en Mundiales.", "Juega de local a 2.800 m de altura en Quito, un fortín temido."] },
  Paraguay: { es: "Paraguay", flag: "🇵🇾", code: "PY", confed: "CONMEBOL", nick: "La Albirroja", c1: "#D52B1E", c2: "#FFFFFF", c3: "#0038A8", titles: "Mejor: cuartos en 2010", facts: ["Volvió a un Mundial tras 16 años de ausencia.", "En 2010 cayó en cuartos solo ante la España campeona.", "José Luis Chilavert, su arquero goleador, es leyenda del fútbol."] },
  USA: { es: "Estados Unidos", flag: "🇺🇸", code: "US", confed: "CONCACAF", nick: "The Stars and Stripes", c1: "#0A3161", c2: "#B31942", c3: "#FFFFFF", titles: "Anfitrión · 3.° en 1930", facts: ["Es uno de los tres países anfitriones del Mundial 2026.", "Tiene una camada joven que juega en las grandes ligas de Europa.", "El soccer crece a pasos agigantados de la mano de la MLS y Messi en Miami."] },
  Mexico: { es: "México", flag: "🇲🇽", code: "MX", confed: "CONCACAF", nick: "El Tri", c1: "#006847", c2: "#CE1126", c3: "#FFFFFF", titles: "Anfitrión · cuartos 1970 y 1986", facts: ["Será el primer país en organizar tres Copas del Mundo (1970, 1986 y 2026).", "El estadio Azteca abrirá el Mundial el 11 de junio de 2026.", "El 'Tri' clasificó a casi todos los Mundiales de las últimas décadas."] },
  Canada: { es: "Canadá", flag: "🇨🇦", code: "CA", confed: "CONCACAF", nick: "Les Rouges", c1: "#FF0000", c2: "#FFFFFF", c3: "#A6192E", titles: "Anfitrión", facts: ["Es coanfitrión por primera vez de un Mundial masculino.", "Alphonso Davies, del Bayern Múnich, es su gran estrella.", "Vive su mejor momento futbolístico de la historia."] },
  Morocco: { es: "Marruecos", flag: "🇲🇦", code: "MA", confed: "CAF", nick: "Los Leones del Atlas", c1: "#C1272D", c2: "#006233", c3: "#FFFFFF", titles: "4.° en 2022 · histórico", facts: ["En Qatar 2022 fue el primer país africano en llegar a semifinales.", "Dejó en el camino a España y Portugal en aquella gesta inolvidable.", "Su hinchada fue una de las más numerosas y ruidosas de Qatar."] },
  Senegal: { es: "Senegal", flag: "🇸🇳", code: "SN", confed: "CAF", nick: "Los Leones de Teranga", c1: "#00853F", c2: "#FDEF42", c3: "#E31B23", titles: "Cuartos en 2002", facts: ["En su debut mundialista (2002) venció al campeón Francia y llegó a cuartos.", "Campeón de África en 2021, ganando su primera Copa Africana.", "Sadio Mané es el emblema de esta generación dorada."] },
  Tunisia: { es: "Túnez", flag: "🇹🇳", code: "TN", confed: "CAF", nick: "Las Águilas de Cartago", c1: "#E70013", c2: "#FFFFFF", c3: "#C8102E", titles: "Fase de grupos", facts: ["En 2022 venció a la campeona del mundo Francia por 1-0.", "Fue el primer equipo africano en ganar un partido en un Mundial (1978).", "Su hinchada llena los estadios con cánticos y tambores."] },
  Egypt: { es: "Egipto", flag: "🇪🇬", code: "EG", confed: "CAF", nick: "Los Faraones", c1: "#CE1126", c2: "#FFFFFF", c3: "#000000", titles: "7 veces campeón de África", facts: ["Mohamed Salah, estrella del Liverpool, lidera al equipo.", "Es la selección con más títulos de la Copa Africana (7).", "Volvió a un Mundial tras 28 años en Rusia 2018."] },
  Algeria: { es: "Argelia", flag: "🇩🇿", code: "DZ", confed: "CAF", nick: "Los Zorros del Desierto", c1: "#007229", c2: "#FFFFFF", c3: "#D21034", titles: "Octavos en 2014", facts: ["En 2014 jugó de igual a igual ante la Alemania que sería campeona.", "Campeón de África en 2019.", "En 1982 protagonizó una de las mayores sorpresas venciendo a Alemania."] },
  Ghana: { es: "Ghana", flag: "🇬🇭", code: "GH", confed: "CAF", nick: "Las Estrellas Negras", c1: "#006B3F", c2: "#FCD116", c3: "#CE1126", titles: "Cuartos en 2010", facts: ["En 2010 estuvo a un penal de ser el primer semifinalista africano.", "Aquel penal atajado a Asamoah Gyan quedó en la memoria del continente.", "Cuádruple campeón de África."] },
  "Ivory Coast": { es: "Costa de Marfil", flag: "🇨🇮", code: "CI", confed: "CAF", nick: "Los Elefantes", c1: "#F77F00", c2: "#FFFFFF", c3: "#009E60", titles: "Campeón de África 2024", facts: ["Campeón de África en 2024 jugando de local, tras una remontada épica.", "Didier Drogba fue su máximo ídolo y goleador histórico.", "Tiene una de las camisetas naranjas más icónicas del continente."] },
  "Cape Verde": { es: "Cabo Verde", flag: "🇨🇻", code: "CV", confed: "CAF", nick: "Los Tiburones Azules", c1: "#003893", c2: "#FFFFFF", c3: "#CF2027", titles: "Debut mundialista", facts: ["Clasifica por PRIMERA vez en su historia a un Mundial.", "Es uno de los países más pequeños en llegar a una Copa del Mundo (~500 mil hab.).", "Su clasificación fue una de las grandes historias de las Eliminatorias."] },
  "South Africa": { es: "Sudáfrica", flag: "🇿🇦", code: "ZA", confed: "CAF", nick: "Bafana Bafana", c1: "#007749", c2: "#FFB81C", c3: "#DE3831", titles: "Anfitrión 2010", facts: ["Organizó el primer Mundial en suelo africano en 2010, el de las vuvuzelas.", "El gol de Tshabalala abrió aquel torneo con un golazo inolvidable.", "Vuelve a un Mundial tras varios años de ausencia."] },
  "DR Congo": { es: "RD del Congo", flag: "🇨🇩", code: "CD", confed: "CAF", nick: "Los Leopardos", c1: "#007FFF", c2: "#F7D618", c3: "#CE1021", titles: "Octavos en 1974", facts: ["Como Zaire, fue el primer país del África subsahariana en un Mundial (1974).", "Subcampeón de la Copa Africana en ediciones recientes.", "Tiene una camada de jugadores en las mejores ligas europeas."] },
  Japan: { es: "Japón", flag: "🇯🇵", code: "JP", confed: "AFC", nick: "Los Samuráis Azules", c1: "#0B1F8F", c2: "#FFFFFF", c3: "#BC002D", titles: "Octavos (4 veces)", facts: ["En 2022 venció a Alemania Y a España en la misma fase de grupos.", "Su hinchada es famosa por limpiar las tribunas después de cada partido.", "Sueña con romper el techo de los octavos de final."] },
  "South Korea": { es: "Corea del Sur", flag: "🇰🇷", code: "KR", confed: "AFC", nick: "Los Tigres de Asia", c1: "#CD2E3A", c2: "#0047A0", c3: "#000000", titles: "Semifinal en 2002", facts: ["En 2002, como anfitriona, alcanzó las semifinales (su mejor histórico).", "Son Heung-min, capitán y estrella, es ídolo en Inglaterra.", "Clasifica a Mundiales de forma casi ininterrumpida desde 1986."] },
  Iran: { es: "Irán", flag: "🇮🇷", code: "IR", confed: "AFC", nick: "Team Melli", c1: "#239F40", c2: "#FFFFFF", c3: "#DA0000", titles: "Fase de grupos", facts: ["Es una de las potencias históricas del fútbol asiático.", "En 1998 logró una recordada victoria ante Estados Unidos.", "Suele tener una de las defensas más ordenadas de Asia."] },
  "Saudi Arabia": { es: "Arabia Saudita", flag: "🇸🇦", code: "SA", confed: "AFC", nick: "Los Halcones Verdes", c1: "#006C35", c2: "#FFFFFF", c3: "#1A8A4A", titles: "Octavos en 1994", facts: ["En Qatar 2022 dio el batacazo venciendo 2-1 a la Argentina que sería campeona.", "Su liga atrajo a estrellas mundiales como Cristiano Ronaldo y Benzema.", "Será sede del Mundial 2034."] },
  Australia: { es: "Australia", flag: "🇦🇺", code: "AU", confed: "AFC", nick: "Los Socceroos", c1: "#00843D", c2: "#FFCD00", c3: "#00247D", titles: "Octavos 2006 y 2022", facts: ["Pasó de Oceanía a Asia (AFC) para tener competencia más fuerte.", "En 2022 superó la fase de grupos por segunda vez en su historia.", "Es la potencia futbolística de Oceanía pese a competir en Asia."] },
  Qatar: { es: "Catar", flag: "🇶🇦", code: "QA", confed: "AFC", nick: "Los Marrón", c1: "#8A1538", c2: "#FFFFFF", c3: "#7A1230", titles: "Anfitrión 2022", facts: ["Organizó el Mundial 2022, el primero en Medio Oriente.", "Campeón de Asia en 2019 y 2023.", "Clasifica a su segundo Mundial consecutivo, ahora por mérito deportivo."] },
  Uzbekistan: { es: "Uzbekistán", flag: "🇺🇿", code: "UZ", confed: "AFC", nick: "Los Lobos Blancos", c1: "#1EB53A", c2: "#FFFFFF", c3: "#0099B5", titles: "Debut mundialista", facts: ["Clasifica por PRIMERA vez en su historia a una Copa del Mundo.", "Su generación juvenil viene de brillar en torneos sub-20 y sub-23.", "Una de las grandes revelaciones del fútbol asiático."] },
  Jordan: { es: "Jordania", flag: "🇯🇴", code: "JO", confed: "AFC", nick: "Los Caballeros de Nashama", c1: "#007A3D", c2: "#FFFFFF", c3: "#CE1126", titles: "Debut mundialista", facts: ["Clasifica por PRIMERA vez en su historia a un Mundial.", "Fue finalista sorpresa de la Copa Asia 2023.", "Su clasificación desató una fiesta histórica en Amán."] },
  Iraq: { es: "Irak", flag: "🇮🇶", code: "IQ", confed: "AFC", nick: "Los Leones de Mesopotamia", c1: "#007A3D", c2: "#FFFFFF", c3: "#CE1126", titles: "Campeón de Asia 2007", facts: ["Ganó la Copa Asia 2007 en medio de un contexto durísimo, uniendo al país.", "Vuelve a un Mundial tras su única participación en 1986.", "Su título asiático es una de las historias más emotivas del fútbol."] },
  Switzerland: { es: "Suiza", flag: "🇨🇭", code: "CH", confed: "UEFA", nick: "La Nati", c1: "#D52B1E", c2: "#FFFFFF", c3: "#FF0000", titles: "Cuartos 1934, 1938, 1954", facts: ["Eliminó a Francia, campeona del mundo, en la Euro 2020 por penales.", "Es un equipo extremadamente regular: clasifica a casi todos los torneos.", "Granit Xhaka es el líder y capitán de la generación actual."] },
  Austria: { es: "Austria", flag: "🇦🇹", code: "AT", confed: "UEFA", nick: "Das Team", c1: "#ED2939", c2: "#FFFFFF", c3: "#C8102E", titles: "3.° en 1954", facts: ["Su mejor histórico fue el tercer puesto en el Mundial de 1954.", "Juega un fútbol intenso de presión alta muy difícil de enfrentar.", "David Alaba es una de sus máximas figuras."] },
  "Czech Republic": { es: "Rep. Checa", flag: "🇨🇿", code: "CZ", confed: "UEFA", nick: "Národní tým", c1: "#D7141A", c2: "#FFFFFF", c3: "#11457E", titles: "Subcampeón Euro 1996", facts: ["Como Checoslovaquia fue subcampeón mundial en 1934 y 1962.", "Subcampeón de la Eurocopa 1996 con la generación de Nedvěd.", "Vuelve a un Mundial tras varios años de ausencia."] },
  "Bosnia-Herzegovina": { es: "Bosnia y Herz.", flag: "🇧🇦", code: "BA", confed: "UEFA", nick: "Los Dragones", c1: "#002F6C", c2: "#FECB00", c3: "#FFFFFF", titles: "Fase de grupos 2014", facts: ["Su único Mundial fue Brasil 2014, donde Edin Džeko brilló.", "Es una de las selecciones más jóvenes como nación independiente.", "Su clasificación volvió a unir a todo el país en la cancha."] },
  Scotland: { es: "Escocia", flag: "🏴", code: "GB-SCT", confed: "UEFA", nick: "The Tartan Army", c1: "#0065BF", c2: "#FFFFFF", c3: "#003B7F", titles: "Histórico mundialista", facts: ["Su hinchada, el 'Tartan Army', es de las más queridas y fiesteras del mundo.", "Vuelve a un Mundial tras una larguísima sequía.", "Es una de las naciones más antiguas del fútbol: jugó el primer partido internacional (1872)."] },
  Norway: { es: "Noruega", flag: "🇳🇴", code: "NO", confed: "UEFA", nick: "Los Vikingos", c1: "#BA0C2F", c2: "#FFFFFF", c3: "#00205B", titles: "Octavos en 1998", facts: ["Vuelve a un Mundial tras 28 años, de la mano de Erling Haaland.", "Haaland es uno de los goleadores más letales del planeta.", "Con Haaland y Ødegaard tiene una de las duplas más temidas."] },
  Sweden: { es: "Suecia", flag: "🇸🇪", code: "SE", confed: "UEFA", nick: "Blågult", c1: "#006AA7", c2: "#FECC00", c3: "#004B87", titles: "Subcampeón 1958", facts: ["Fue subcampeón del mundo en casa en 1958, perdiendo ante el Brasil de Pelé.", "En 1994 logró un histórico tercer puesto.", "Tiene una de las hinchadas más numerosas de Escandinavia."] },
  Turkey: { es: "Turquía", flag: "🇹🇷", code: "TR", confed: "UEFA", nick: "La Media Luna", c1: "#E30A17", c2: "#FFFFFF", c3: "#C8102E", titles: "3.° en 2002", facts: ["En su mejor actuación logró el tercer puesto en 2002.", "Hakan Şükür marcó el gol más rápido de la historia de los Mundiales (11 segundos).", "Tiene una camada joven y talentosa con Arda Güler a la cabeza."] },
  "New Zealand": { es: "Nueva Zelanda", flag: "🇳🇿", code: "NZ", confed: "OFC", nick: "Los All Whites", c1: "#FFFFFF", c2: "#000000", c3: "#C8102E", titles: "Invicto en 2010", facts: ["En 2010 fue el único equipo que terminó invicto el Mundial (3 empates) ¡y quedó afuera!", "Es la gran potencia de Oceanía (OFC).", "Comparte el apodo 'All Whites' como guiño a los All Blacks del rugby."] },
  Haiti: { es: "Haití", flag: "🇭🇹", code: "HT", confed: "CONCACAF", nick: "Les Grenadiers", c1: "#00209F", c2: "#D21034", c3: "#FFFFFF", titles: "Mundialista 1974", facts: ["Vuelve a un Mundial tras más de 50 años (su único antecedente fue 1974).", "En 1974, Emmanuel Sanon le cortó un invicto histórico al arquero italiano Zoff.", "Su clasificación fue una alegría enorme en medio de un contexto muy difícil."] },
  Panama: { es: "Panamá", flag: "🇵🇦", code: "PA", confed: "CONCACAF", nick: "La Marea Roja", c1: "#DA121A", c2: "#FFFFFF", c3: "#005293", titles: "Fase de grupos 2018", facts: ["Su debut mundialista fue Rusia 2018, una fiesta nacional total.", "El día que clasificó por primera vez fue declarado feriado nacional.", "Su hinchada tiñe de rojo cada estadio donde juega."] },
  "Curaçao": { es: "Curazao", flag: "🇨🇼", code: "CW", confed: "CONCACAF", nick: "Los Azules", c1: "#002B7F", c2: "#FFFFFF", c3: "#F9E814", titles: "Debut mundialista", facts: ["Clasifica por PRIMERA vez y es el país más pequeño en llegar a un Mundial (~150 mil hab.).", "Una isla caribeña que escribió una de las páginas más increíbles del fútbol.", "Su clasificación es considerada una de las mayores hazañas de CONCACAF."] },
};

// Mapa código ISO -> nombre de equipo (para autodetección por país)
const CODE_TO_TEAM = {};
for (const [name, t] of Object.entries(TEAMS)) {
  if (t.code) CODE_TO_TEAM[t.code] = name;
}

// Orden alfabético en español para el selector
const TEAM_NAMES_SORTED = Object.keys(TEAMS).sort((a, b) =>
  TEAMS[a].es.localeCompare(TEAMS[b].es, "es")
);
