/* themes.js — Datos temáticos de las 48 selecciones del Mundial 2026.
 * c1 = color dominante, c2 = secundario, c3 = acento.
 * code = ISO alpha-2 (autodetección + bandera vía flagcdn).
 * facts = { es:[...], en:[...] } (pt/fr usan en como respaldo).
 * Los nombres (clave) coinciden EXACTO con los de TheSportsDB.
 */

const NEUTRAL = {
  es: "Mundial 2026", en: "World Cup 2026", flag: "🏆", code: "",
  confed: "FIFA · USA · Canadá · México",
  nick: { es: "La fiesta del fútbol mundial", en: "The world's football party" },
  c1: "#D4AF37", c2: "#0A3161", c3: "#E4002B",
  titles: { es: "48 selecciones · 104 partidos · 16 sedes", en: "48 teams · 104 matches · 16 venues" },
  facts: {
    es: [
      "Es el primer Mundial con 48 selecciones y 104 partidos, el más grande de la historia.",
      "Se juega en 3 países: Estados Unidos, Canadá y México, en 16 ciudades sede.",
      "México es el primer país en albergar partidos de Copa del Mundo en tres ediciones (1970, 1986 y 2026).",
      "La final será el 19 de julio de 2026 en el MetLife Stadium (Nueva Jersey).",
    ],
    en: [
      "The first 48-team, 104-match World Cup — the biggest in history.",
      "Played across 3 countries: USA, Canada and Mexico, in 16 host cities.",
      "Mexico becomes the first nation to host World Cup matches in three editions (1970, 1986, 2026).",
      "The final is on July 19, 2026 at MetLife Stadium (New Jersey).",
    ],
  },
};

const TEAMS = {
  Argentina: { es: "Argentina", en: "Argentina", code: "AR", confed: "CONMEBOL", nick: { es: "La Albiceleste", en: "La Albiceleste" }, c1: "#6CB4E4", c2: "#FFFFFF", c3: "#F6B40E", titles: { es: "3 Mundiales · 1978, 1986, 2022", en: "3 World Cups · 1978, 1986, 2022" }, facts: { es: ["Llega como campeona defensora tras ganar Qatar 2022 ante Francia por penales.", "Lionel Messi es el jugador con más partidos en la historia de los Mundiales.", "El himno 'Muchachos' fue la banda sonora de la consagración en 2022."], en: ["Defending champions after beating France on penalties at Qatar 2022.", "Lionel Messi has played the most matches in World Cup history.", "Won its third star in 2022 with one of the greatest finals ever."] } },
  Brazil: { es: "Brasil", en: "Brazil", code: "BR", confed: "CONMEBOL", nick: { es: "A Seleção / Verdeamarela", en: "A Seleção" }, c1: "#FFDF00", c2: "#009739", c3: "#002776", titles: { es: "5 Mundiales · récord absoluto", en: "5 World Cups · all-time record" }, facts: { es: ["Es la única selección que jugó TODAS las Copas del Mundo de la historia.", "Pelé es el único futbolista que ganó tres Mundiales (1958, 1962 y 1970).", "Su quinta estrella la consiguió en 2002 con Ronaldo como goleador."], en: ["The only nation to have played in every single World Cup.", "Pelé is the only player to win three World Cups (1958, 1962, 1970).", "Its fifth star came in 2002 with Ronaldo as top scorer."] } },
  France: { es: "Francia", en: "France", code: "FR", confed: "UEFA", nick: { es: "Les Bleus", en: "Les Bleus" }, c1: "#0055A4", c2: "#FFFFFF", c3: "#EF4135", titles: { es: "2 Mundiales · 1998, 2018", en: "2 World Cups · 1998, 2018" }, facts: { es: ["Fue finalista en 2022 y subcampeona tras un partidazo ante Argentina.", "Kylian Mbappé hizo un triplete en la final de 2022, hazaña que solo logró Geoff Hurst (1966).", "Ganó su primer título en casa en 1998 con Zidane como figura."], en: ["Runners-up in 2022 after a classic final against Argentina.", "Mbappé scored a hat-trick in the 2022 final — only Geoff Hurst (1966) had done it before.", "Won its first title at home in 1998 with Zidane starring."] } },
  Spain: { es: "España", en: "Spain", code: "ES", confed: "UEFA", nick: { es: "La Roja", en: "La Roja" }, c1: "#C60B1E", c2: "#FFC400", c3: "#AD1519", titles: { es: "1 Mundial · 2010", en: "1 World Cup · 2010" }, facts: { es: ["Campeona del mundo en 2010 con un gol de Iniesta en la final ante Países Bajos.", "Viene de ganar la Eurocopa 2024 con un fútbol vertiginoso y joven.", "Lamine Yamal irrumpió como una de las grandes joyas del fútbol mundial."], en: ["World champions in 2010 thanks to Iniesta's goal against the Netherlands.", "Reigning Euro 2024 winners with a thrilling young side.", "Lamine Yamal has emerged as one of football's brightest gems."] } },
  Germany: { es: "Alemania", en: "Germany", code: "DE", confed: "UEFA", nick: { es: "Die Mannschaft", en: "Die Mannschaft" }, c1: "#1A1A1A", c2: "#DD0000", c3: "#FFCE00", titles: { es: "4 Mundiales · 1954, 1974, 1990, 2014", en: "4 World Cups · 1954, 1974, 1990, 2014" }, facts: { es: ["Su última estrella fue en Brasil 2014 con el histórico 7-1 a la anfitriona en semis.", "Miroslav Klose es el máximo goleador histórico de los Mundiales con 16 goles.", "Es la selección con más finales disputadas junto a Brasil."], en: ["Its last title came in 2014, including the historic 7-1 over hosts Brazil.", "Miroslav Klose is the World Cup's all-time top scorer with 16 goals.", "Shares the record for most World Cup finals played with Brazil."] } },
  England: { es: "Inglaterra", en: "England", code: "GB", fc: "gb-eng", confed: "UEFA", nick: { es: "The Three Lions", en: "The Three Lions" }, c1: "#FFFFFF", c2: "#CF081F", c3: "#1D3D8F", titles: { es: "1 Mundial · 1966", en: "1 World Cup · 1966" }, facts: { es: ["Su único título fue en casa en 1966 con el recordado 'gol fantasma' de Hurst.", "Harry Kane es el máximo goleador histórico de la selección inglesa.", "Llega tras dos finales de Eurocopa perdidas (2021 y 2024) buscando revancha."], en: ["Its only title came at home in 1966 with Hurst's famous 'ghost goal'.", "Harry Kane is England's all-time leading scorer.", "Arrives after two lost Euro finals (2021, 2024) seeking redemption."] } },
  Portugal: { es: "Portugal", en: "Portugal", code: "PT", confed: "UEFA", nick: { es: "A Seleção das Quinas", en: "Seleção das Quinas" }, c1: "#006600", c2: "#FF0000", c3: "#FFD700", titles: { es: "Mejor: 3.° en 1966", en: "Best: 3rd in 1966" }, facts: { es: ["Cristiano Ronaldo es el máximo goleador de selecciones de la historia.", "Ganó la Eurocopa 2016 y la Nations League 2019 y 2025.", "Tiene una de las generaciones más talentosas con Bruno, Leão y Bernardo Silva."], en: ["Cristiano Ronaldo is the all-time top scorer in men's international football.", "Won Euro 2016 and the Nations League in 2019 and 2025.", "Boasts a golden generation with Bruno, Leão and Bernardo Silva."] } },
  Netherlands: { es: "Países Bajos", en: "Netherlands", code: "NL", confed: "UEFA", nick: { es: "Oranje", en: "Oranje" }, c1: "#FF6200", c2: "#21468B", c3: "#AE1C28", titles: { es: "3 finales · subcampeón 1974, 1978, 2010", en: "3 finals · runners-up 1974, 1978, 2010" }, facts: { es: ["Inventores del 'fútbol total' con Johan Cruyff en los años 70.", "Es la mejor selección que nunca ganó un Mundial, con tres finales perdidas.", "Su marea naranja es una de las hinchadas más vistosas del torneo."], en: ["Pioneers of 'Total Football' with Johan Cruyff in the 1970s.", "The best team never to win a World Cup, with three lost finals.", "Its orange sea of fans is one of the tournament's most colourful."] } },
  Croatia: { es: "Croacia", en: "Croatia", code: "HR", confed: "UEFA", nick: { es: "Vatreni (Los Ardientes)", en: "Vatreni" }, c1: "#FF0000", c2: "#FFFFFF", c3: "#171796", titles: { es: "Subcampeón 2018 · 3.° en 2022", en: "Runners-up 2018 · 3rd in 2022" }, facts: { es: ["Con apenas 4 millones de habitantes llegó a la final en 2018.", "Luka Modrić ganó el Balón de Oro 2018 cortando el reinado de Messi y Cristiano.", "Su camiseta a cuadros rojos y blancos es de las más reconocibles del mundo."], en: ["With just 4 million people, it reached the 2018 final.", "Luka Modrić won the 2018 Ballon d'Or, ending the Messi–Ronaldo era.", "Its red-and-white checkerboard kit is one of the most recognisable."] } },
  Belgium: { es: "Bélgica", en: "Belgium", code: "BE", confed: "UEFA", nick: { es: "Los Diablos Rojos", en: "Red Devils" }, c1: "#E30613", c2: "#1A1A1A", c3: "#FDDA24", titles: { es: "Mejor: 3.° en 2018", en: "Best: 3rd in 2018" }, facts: { es: ["Su 'generación dorada' (De Bruyne, Hazard, Lukaku) alcanzó el podio en 2018.", "Fue número 1 del ranking FIFA durante varios años seguidos.", "Romelu Lukaku es su máximo goleador histórico."], en: ["Its golden generation (De Bruyne, Hazard, Lukaku) reached the podium in 2018.", "Topped the FIFA ranking for several years running.", "Romelu Lukaku is its all-time leading scorer."] } },
  Uruguay: { es: "Uruguay", en: "Uruguay", code: "UY", confed: "CONMEBOL", nick: { es: "La Celeste", en: "La Celeste" }, c1: "#5CBFEB", c2: "#FFFFFF", c3: "#FCD116", titles: { es: "2 Mundiales · 1930, 1950", en: "2 World Cups · 1930, 1950" }, facts: { es: ["Ganó el primer Mundial de la historia, en casa, en 1930.", "El 'Maracanazo' de 1950 es una de las mayores hazañas del fútbol.", "Sus 4 estrellas incluyen los oros olímpicos de 1924 y 1928, reconocidos por FIFA."], en: ["Won the very first World Cup, at home, in 1930.", "The 1950 'Maracanazo' is one of football's greatest upsets.", "Its 4 stars include the 1924 and 1928 Olympic golds recognised by FIFA."] } },
  Colombia: { es: "Colombia", en: "Colombia", code: "CO", confed: "CONMEBOL", nick: { es: "Los Cafeteros", en: "Los Cafeteros" }, c1: "#FCD116", c2: "#003893", c3: "#CE1126", titles: { es: "Mejor: cuartos en 2014", en: "Best: quarters in 2014" }, facts: { es: ["James Rodríguez fue el goleador del Mundial 2014 con un golazo ante Uruguay.", "Llega tras ser finalista de la Copa América 2024.", "La hinchada cafetera es famosa por su alegría y su música."], en: ["James Rodríguez was the 2014 World Cup top scorer with a stunning goal vs Uruguay.", "Arrives after reaching the 2024 Copa América final.", "Its fans are famous for their joy and music."] } },
  Ecuador: { es: "Ecuador", en: "Ecuador", code: "EC", confed: "CONMEBOL", nick: { es: "La Tri", en: "La Tri" }, c1: "#FFD100", c2: "#0072CE", c3: "#EF3340", titles: { es: "Mejor: octavos en 2006", en: "Best: round of 16 in 2006" }, facts: { es: ["Una de las defensas más sólidas de las Eliminatorias sudamericanas.", "Enner Valencia es su máximo goleador histórico en Mundiales.", "Juega de local a 2.800 m de altura en Quito, un fortín temido."], en: ["One of the toughest defences in South American qualifying.", "Enner Valencia is its all-time World Cup top scorer.", "Plays home games at 2,800 m altitude in Quito — a feared fortress."] } },
  Paraguay: { es: "Paraguay", en: "Paraguay", code: "PY", confed: "CONMEBOL", nick: { es: "La Albirroja", en: "La Albirroja" }, c1: "#D52B1E", c2: "#FFFFFF", c3: "#0038A8", titles: { es: "Mejor: cuartos en 2010", en: "Best: quarters in 2010" }, facts: { es: ["Volvió a un Mundial tras 16 años de ausencia.", "En 2010 cayó en cuartos solo ante la España campeona.", "José Luis Chilavert, su arquero goleador, es leyenda del fútbol."], en: ["Back at a World Cup after a 16-year absence.", "In 2010 it lost in the quarters only to eventual champions Spain.", "Goalkeeper-scorer José Luis Chilavert is a football legend."] } },
  USA: { es: "Estados Unidos", en: "United States", code: "US", confed: "CONCACAF", nick: { es: "The Stars and Stripes", en: "Stars and Stripes" }, c1: "#0A3161", c2: "#B31942", c3: "#FFFFFF", titles: { es: "Anfitrión · 3.° en 1930", en: "Host · 3rd in 1930" }, facts: { es: ["Es uno de los tres países anfitriones del Mundial 2026.", "Tiene una camada joven que juega en las grandes ligas de Europa.", "El soccer crece a pasos agigantados de la mano de la MLS y Messi en Miami."], en: ["One of the three host nations of the 2026 World Cup.", "Has a young core playing in Europe's top leagues.", "Soccer is booming thanks to MLS and Messi in Miami."] } },
  Mexico: { es: "México", en: "Mexico", code: "MX", confed: "CONCACAF", nick: { es: "El Tri", en: "El Tri" }, c1: "#006847", c2: "#CE1126", c3: "#FFFFFF", titles: { es: "Anfitrión · cuartos 1970 y 1986", en: "Host · quarters 1970 & 1986" }, facts: { es: ["Será el primer país en organizar tres Copas del Mundo (1970, 1986 y 2026).", "El estadio Azteca abrirá el Mundial el 11 de junio de 2026.", "El 'Tri' clasificó a casi todos los Mundiales de las últimas décadas."], en: ["The first country to host three World Cups (1970, 1986, 2026).", "Estadio Azteca opens the tournament on June 11, 2026.", "El Tri has qualified for almost every recent World Cup."] } },
  Canada: { es: "Canadá", en: "Canada", code: "CA", confed: "CONCACAF", nick: { es: "Les Rouges", en: "The Reds" }, c1: "#FF0000", c2: "#FFFFFF", c3: "#A6192E", titles: { es: "Anfitrión", en: "Host" }, facts: { es: ["Es coanfitrión por primera vez de un Mundial masculino.", "Alphonso Davies, del Bayern Múnich, es su gran estrella.", "Vive su mejor momento futbolístico de la historia."], en: ["Co-hosting a men's World Cup for the first time.", "Bayern Munich's Alphonso Davies is its star man.", "Living the best football era in its history."] } },
  Morocco: { es: "Marruecos", en: "Morocco", code: "MA", confed: "CAF", nick: { es: "Los Leones del Atlas", en: "Atlas Lions" }, c1: "#C1272D", c2: "#006233", c3: "#FFFFFF", titles: { es: "4.° en 2022 · histórico", en: "4th in 2022 · historic" }, facts: { es: ["En Qatar 2022 fue el primer país africano en llegar a semifinales.", "Dejó en el camino a España y Portugal en aquella gesta inolvidable.", "Su hinchada fue una de las más numerosas y ruidosas de Qatar."], en: ["At Qatar 2022 it became the first African nation to reach the semis.", "It knocked out Spain and Portugal on that unforgettable run.", "Its fans were among the loudest and largest in Qatar."] } },
  Senegal: { es: "Senegal", en: "Senegal", code: "SN", confed: "CAF", nick: { es: "Los Leones de Teranga", en: "Lions of Teranga" }, c1: "#00853F", c2: "#FDEF42", c3: "#E31B23", titles: { es: "Cuartos en 2002", en: "Quarters in 2002" }, facts: { es: ["En su debut mundialista (2002) venció al campeón Francia y llegó a cuartos.", "Campeón de África en 2021, ganando su primera Copa Africana.", "Sadio Mané es el emblema de esta generación dorada."], en: ["On its 2002 debut it beat champions France and reached the quarters.", "Won its first Africa Cup of Nations in 2021.", "Sadio Mané is the emblem of this golden generation."] } },
  Tunisia: { es: "Túnez", en: "Tunisia", code: "TN", confed: "CAF", nick: { es: "Las Águilas de Cartago", en: "Eagles of Carthage" }, c1: "#E70013", c2: "#FFFFFF", c3: "#C8102E", titles: { es: "Fase de grupos", en: "Group stage" }, facts: { es: ["En 2022 venció a la campeona del mundo Francia por 1-0.", "Fue el primer equipo africano en ganar un partido en un Mundial (1978).", "Su hinchada llena los estadios con cánticos y tambores."], en: ["In 2022 it beat world champions France 1-0.", "First African team to win a World Cup match (1978).", "Its fans fill stadiums with chants and drums."] } },
  Egypt: { es: "Egipto", en: "Egypt", code: "EG", confed: "CAF", nick: { es: "Los Faraones", en: "The Pharaohs" }, c1: "#CE1126", c2: "#FFFFFF", c3: "#1A1A1A", titles: { es: "7 veces campeón de África", en: "7-time African champions" }, facts: { es: ["Mohamed Salah, estrella del Liverpool, lidera al equipo.", "Es la selección con más títulos de la Copa Africana (7).", "Volvió a un Mundial tras 28 años en Rusia 2018."], en: ["Liverpool star Mohamed Salah leads the team.", "Record 7-time Africa Cup of Nations winners.", "Returned to the World Cup in 2018 after 28 years."] } },
  Algeria: { es: "Argelia", en: "Algeria", code: "DZ", confed: "CAF", nick: { es: "Los Zorros del Desierto", en: "Desert Foxes" }, c1: "#007229", c2: "#FFFFFF", c3: "#D21034", titles: { es: "Octavos en 2014", en: "Round of 16 in 2014" }, facts: { es: ["En 2014 jugó de igual a igual ante la Alemania que sería campeona.", "Campeón de África en 2019.", "En 1982 protagonizó una de las mayores sorpresas venciendo a Alemania."], en: ["In 2014 it went toe-to-toe with eventual champions Germany.", "Africa Cup of Nations winners in 2019.", "In 1982 it pulled off a famous upset beating West Germany."] } },
  Ghana: { es: "Ghana", en: "Ghana", code: "GH", confed: "CAF", nick: { es: "Las Estrellas Negras", en: "Black Stars" }, c1: "#006B3F", c2: "#FCD116", c3: "#CE1126", titles: { es: "Cuartos en 2010", en: "Quarters in 2010" }, facts: { es: ["En 2010 estuvo a un penal de ser el primer semifinalista africano.", "Aquel penal atajado a Asamoah Gyan quedó en la memoria del continente.", "Cuádruple campeón de África."], en: ["In 2010 it was one penalty from being Africa's first semi-finalist.", "Gyan's missed penalty remains seared in the continent's memory.", "Four-time African champions."] } },
  "Ivory Coast": { es: "Costa de Marfil", en: "Ivory Coast", code: "CI", confed: "CAF", nick: { es: "Los Elefantes", en: "The Elephants" }, c1: "#F77F00", c2: "#FFFFFF", c3: "#009E60", titles: { es: "Campeón de África 2024", en: "African champions 2024" }, facts: { es: ["Campeón de África en 2024 jugando de local, tras una remontada épica.", "Didier Drogba fue su máximo ídolo y goleador histórico.", "Tiene una de las camisetas naranjas más icónicas del continente."], en: ["Won the 2024 Cup of Nations at home after an epic comeback.", "Didier Drogba is its greatest idol and top scorer.", "Wears one of Africa's most iconic orange shirts."] } },
  "Cape Verde": { es: "Cabo Verde", en: "Cape Verde", code: "CV", confed: "CAF", nick: { es: "Los Tiburones Azules", en: "Blue Sharks" }, c1: "#003893", c2: "#FFFFFF", c3: "#CF2027", titles: { es: "Debut mundialista", en: "World Cup debut" }, facts: { es: ["Clasifica por PRIMERA vez en su historia a un Mundial.", "Es uno de los países más pequeños en llegar a una Copa del Mundo (~500 mil hab.).", "Su clasificación fue una de las grandes historias de las Eliminatorias."], en: ["Qualifies for a World Cup for the very FIRST time.", "One of the smallest nations ever to reach a World Cup (~500k people).", "Its qualification was one of the great stories of the campaign."] } },
  "South Africa": { es: "Sudáfrica", en: "South Africa", code: "ZA", confed: "CAF", nick: { es: "Bafana Bafana", en: "Bafana Bafana" }, c1: "#007749", c2: "#FFB81C", c3: "#DE3831", titles: { es: "Anfitrión 2010", en: "Host 2010" }, facts: { es: ["Organizó el primer Mundial en suelo africano en 2010, el de las vuvuzelas.", "El gol de Tshabalala abrió aquel torneo con un golazo inolvidable.", "Vuelve a un Mundial tras varios años de ausencia."], en: ["Hosted the first World Cup on African soil in 2010 — the vuvuzela one.", "Tshabalala's stunner opened that tournament.", "Returns to the World Cup after several years away."] } },
  "DR Congo": { es: "RD del Congo", en: "DR Congo", code: "CD", confed: "CAF", nick: { es: "Los Leopardos", en: "The Leopards" }, c1: "#007FFF", c2: "#F7D618", c3: "#CE1021", titles: { es: "Octavos en 1974", en: "Round of 16 in 1974" }, facts: { es: ["Como Zaire, fue el primer país del África subsahariana en un Mundial (1974).", "Subcampeón de la Copa Africana en ediciones recientes.", "Tiene una camada de jugadores en las mejores ligas europeas."], en: ["As Zaire, it was Sub-Saharan Africa's first World Cup team (1974).", "Recent Africa Cup of Nations runners-up.", "Has a crop of players in Europe's best leagues."] } },
  Japan: { es: "Japón", en: "Japan", code: "JP", confed: "AFC", nick: { es: "Los Samuráis Azules", en: "Samurai Blue" }, c1: "#0B1F8F", c2: "#FFFFFF", c3: "#BC002D", titles: { es: "Octavos (4 veces)", en: "Round of 16 (x4)" }, facts: { es: ["En 2022 venció a Alemania Y a España en la misma fase de grupos.", "Su hinchada es famosa por limpiar las tribunas después de cada partido.", "Sueña con romper el techo de los octavos de final."], en: ["In 2022 it beat both Germany and Spain in the group stage.", "Its fans are famous for cleaning the stands after every match.", "Dreams of finally breaking past the round of 16."] } },
  "South Korea": { es: "Corea del Sur", en: "South Korea", code: "KR", confed: "AFC", nick: { es: "Los Tigres de Asia", en: "Taegeuk Warriors" }, c1: "#CD2E3A", c2: "#0047A0", c3: "#1A1A1A", titles: { es: "Semifinal en 2002", en: "Semi-final in 2002" }, facts: { es: ["En 2002, como anfitriona, alcanzó las semifinales (su mejor histórico).", "Son Heung-min, capitán y estrella, es ídolo en Inglaterra.", "Clasifica a Mundiales de forma casi ininterrumpida desde 1986."], en: ["As 2002 hosts it reached the semi-finals — its best ever.", "Captain Son Heung-min is a star in England.", "Has qualified almost continuously since 1986."] } },
  Iran: { es: "Irán", en: "Iran", code: "IR", confed: "AFC", nick: { es: "Team Melli", en: "Team Melli" }, c1: "#239F40", c2: "#FFFFFF", c3: "#DA0000", titles: { es: "Fase de grupos", en: "Group stage" }, facts: { es: ["Es una de las potencias históricas del fútbol asiático.", "En 1998 logró una recordada victoria ante Estados Unidos.", "Suele tener una de las defensas más ordenadas de Asia."], en: ["One of Asian football's historic powers.", "Recorded a famous win over the USA in 1998.", "Usually one of Asia's most organised defences."] } },
  "Saudi Arabia": { es: "Arabia Saudita", en: "Saudi Arabia", code: "SA", confed: "AFC", nick: { es: "Los Halcones Verdes", en: "Green Falcons" }, c1: "#006C35", c2: "#FFFFFF", c3: "#1A8A4A", titles: { es: "Octavos en 1994", en: "Round of 16 in 1994" }, facts: { es: ["En Qatar 2022 dio el batacazo venciendo 2-1 a la Argentina que sería campeona.", "Su liga atrajo a estrellas mundiales como Cristiano Ronaldo y Benzema.", "Será sede del Mundial 2034."], en: ["At Qatar 2022 it stunned eventual champions Argentina 2-1.", "Its league signed stars like Cristiano Ronaldo and Benzema.", "Will host the 2034 World Cup."] } },
  Australia: { es: "Australia", en: "Australia", code: "AU", confed: "AFC", nick: { es: "Los Socceroos", en: "Socceroos" }, c1: "#00843D", c2: "#FFCD00", c3: "#00247D", titles: { es: "Octavos 2006 y 2022", en: "Round of 16 in 2006 & 2022" }, facts: { es: ["Pasó de Oceanía a Asia (AFC) para tener competencia más fuerte.", "En 2022 superó la fase de grupos por segunda vez en su historia.", "Es la potencia futbolística de Oceanía pese a competir en Asia."], en: ["Moved from Oceania to Asia (AFC) for tougher competition.", "Reached the knockouts for the second time in 2022.", "Oceania's football power despite competing in Asia."] } },
  Qatar: { es: "Catar", en: "Qatar", code: "QA", confed: "AFC", nick: { es: "Los Marrón", en: "The Maroon" }, c1: "#8A1538", c2: "#FFFFFF", c3: "#7A1230", titles: { es: "Anfitrión 2022", en: "Host 2022" }, facts: { es: ["Organizó el Mundial 2022, el primero en Medio Oriente.", "Campeón de Asia en 2019 y 2023.", "Clasifica a su segundo Mundial, ahora por mérito deportivo."], en: ["Hosted the 2022 World Cup, the first in the Middle East.", "Asian champions in 2019 and 2023.", "Reaches its second World Cup, now on merit."] } },
  Uzbekistan: { es: "Uzbekistán", en: "Uzbekistan", code: "UZ", confed: "AFC", nick: { es: "Los Lobos Blancos", en: "White Wolves" }, c1: "#1EB53A", c2: "#FFFFFF", c3: "#0099B5", titles: { es: "Debut mundialista", en: "World Cup debut" }, facts: { es: ["Clasifica por PRIMERA vez en su historia a una Copa del Mundo.", "Su generación juvenil viene de brillar en torneos sub-20 y sub-23.", "Una de las grandes revelaciones del fútbol asiático."], en: ["Qualifies for a World Cup for the very FIRST time.", "Its youth sides have shone at U-20 and U-23 level.", "One of Asian football's big revelations."] } },
  Jordan: { es: "Jordania", en: "Jordan", code: "JO", confed: "AFC", nick: { es: "Los Caballeros de Nashama", en: "Al-Nashama" }, c1: "#007A3D", c2: "#FFFFFF", c3: "#CE1126", titles: { es: "Debut mundialista", en: "World Cup debut" }, facts: { es: ["Clasifica por PRIMERA vez en su historia a un Mundial.", "Fue finalista sorpresa de la Copa Asia 2023.", "Su clasificación desató una fiesta histórica en Amán."], en: ["Qualifies for a World Cup for the very FIRST time.", "Surprise finalists at the 2023 Asian Cup.", "Its qualification sparked historic celebrations in Amman."] } },
  Iraq: { es: "Irak", en: "Iraq", code: "IQ", confed: "AFC", nick: { es: "Los Leones de Mesopotamia", en: "Lions of Mesopotamia" }, c1: "#007A3D", c2: "#FFFFFF", c3: "#CE1126", titles: { es: "Campeón de Asia 2007", en: "Asian champions 2007" }, facts: { es: ["Ganó la Copa Asia 2007 en medio de un contexto durísimo, uniendo al país.", "Vuelve a un Mundial tras su única participación en 1986.", "Su título asiático es una de las historias más emotivas del fútbol."], en: ["Won the 2007 Asian Cup in dire circumstances, uniting the country.", "Returns to the World Cup after its lone 1986 appearance.", "Its Asian title is one of football's most moving stories."] } },
  Switzerland: { es: "Suiza", en: "Switzerland", code: "CH", confed: "UEFA", nick: { es: "La Nati", en: "La Nati" }, c1: "#D52B1E", c2: "#FFFFFF", c3: "#FF0000", titles: { es: "Cuartos 1934, 1938, 1954", en: "Quarters 1934, 1938, 1954" }, facts: { es: ["Eliminó a Francia, campeona del mundo, en la Euro 2020 por penales.", "Es un equipo extremadamente regular: clasifica a casi todos los torneos.", "Granit Xhaka es el líder y capitán de la generación actual."], en: ["Knocked out world champions France at Euro 2020 on penalties.", "Remarkably consistent — qualifies for almost every tournament.", "Granit Xhaka leads the current generation."] } },
  Austria: { es: "Austria", en: "Austria", code: "AT", confed: "UEFA", nick: { es: "Das Team", en: "Das Team" }, c1: "#ED2939", c2: "#FFFFFF", c3: "#C8102E", titles: { es: "3.° en 1954", en: "3rd in 1954" }, facts: { es: ["Su mejor histórico fue el tercer puesto en el Mundial de 1954.", "Juega un fútbol intenso de presión alta muy difícil de enfrentar.", "David Alaba es una de sus máximas figuras."], en: ["Its best finish was third place at the 1954 World Cup.", "Plays an intense, high-pressing style that's tough to face.", "David Alaba is one of its biggest stars."] } },
  "Czech Republic": { es: "Rep. Checa", en: "Czechia", code: "CZ", confed: "UEFA", nick: { es: "Národní tým", en: "Národní tým" }, c1: "#D7141A", c2: "#FFFFFF", c3: "#11457E", titles: { es: "Subcampeón Euro 1996", en: "Euro 1996 runners-up" }, facts: { es: ["Como Checoslovaquia fue subcampeón mundial en 1934 y 1962.", "Subcampeón de la Eurocopa 1996 con la generación de Nedvěd.", "Vuelve a un Mundial tras varios años de ausencia."], en: ["As Czechoslovakia it was World Cup runner-up in 1934 and 1962.", "Euro 1996 runners-up with Nedvěd's generation.", "Returns to a World Cup after several years away."] } },
  "Bosnia-Herzegovina": { es: "Bosnia y Herz.", en: "Bosnia & Herz.", code: "BA", confed: "UEFA", nick: { es: "Los Dragones", en: "The Dragons" }, c1: "#002F6C", c2: "#FECB00", c3: "#FFFFFF", titles: { es: "Fase de grupos 2014", en: "Group stage 2014" }, facts: { es: ["Su único Mundial fue Brasil 2014, donde Edin Džeko brilló.", "Es una de las selecciones más jóvenes como nación independiente.", "Su clasificación volvió a unir a todo el país en la cancha."], en: ["Its only World Cup was Brazil 2014, where Edin Džeko shone.", "One of the youngest nations as an independent country.", "Qualifying again united the whole country."] } },
  Scotland: { es: "Escocia", en: "Scotland", code: "GB-SCT", fc: "gb-sct", confed: "UEFA", nick: { es: "The Tartan Army", en: "The Tartan Army" }, c1: "#0065BF", c2: "#FFFFFF", c3: "#003B7F", titles: { es: "Histórico mundialista", en: "Historic side" }, facts: { es: ["Su hinchada, el 'Tartan Army', es de las más queridas y fiesteras del mundo.", "Vuelve a un Mundial tras una larguísima sequía.", "Es una de las naciones más antiguas del fútbol: jugó el primer partido internacional (1872)."], en: ["Its 'Tartan Army' is one of the most beloved fanbases in the world.", "Returns to a World Cup after a very long drought.", "One of football's oldest nations — played the first-ever international (1872)."] } },
  Norway: { es: "Noruega", en: "Norway", code: "NO", confed: "UEFA", nick: { es: "Los Vikingos", en: "The Vikings" }, c1: "#BA0C2F", c2: "#FFFFFF", c3: "#00205B", titles: { es: "Octavos en 1998", en: "Round of 16 in 1998" }, facts: { es: ["Vuelve a un Mundial tras 28 años, de la mano de Erling Haaland.", "Haaland es uno de los goleadores más letales del planeta.", "Con Haaland y Ødegaard tiene una de las duplas más temidas."], en: ["Back at a World Cup after 28 years, led by Erling Haaland.", "Haaland is one of the most lethal scorers on the planet.", "Haaland and Ødegaard form one of the most feared duos."] } },
  Sweden: { es: "Suecia", en: "Sweden", code: "SE", confed: "UEFA", nick: { es: "Blågult", en: "Blågult" }, c1: "#006AA7", c2: "#FECC00", c3: "#004B87", titles: { es: "Subcampeón 1958", en: "Runners-up 1958" }, facts: { es: ["Fue subcampeón del mundo en casa en 1958, perdiendo ante el Brasil de Pelé.", "En 1994 logró un histórico tercer puesto.", "Tiene una de las hinchadas más numerosas de Escandinavia."], en: ["Runners-up at home in 1958, losing to Pelé's Brazil.", "Earned a historic third place in 1994.", "Brings one of Scandinavia's largest fanbases."] } },
  Turkey: { es: "Turquía", en: "Türkiye", code: "TR", confed: "UEFA", nick: { es: "La Media Luna", en: "The Crescent-Stars" }, c1: "#E30A17", c2: "#FFFFFF", c3: "#C8102E", titles: { es: "3.° en 2002", en: "3rd in 2002" }, facts: { es: ["En su mejor actuación logró el tercer puesto en 2002.", "Hakan Şükür marcó el gol más rápido de la historia de los Mundiales (11 segundos).", "Tiene una camada joven con Arda Güler a la cabeza."], en: ["Its best run was third place in 2002.", "Hakan Şükür scored the fastest goal in World Cup history (11 seconds).", "Has a young core led by Arda Güler."] } },
  "New Zealand": { es: "Nueva Zelanda", en: "New Zealand", code: "NZ", confed: "OFC", nick: { es: "Los All Whites", en: "All Whites" }, c1: "#FFFFFF", c2: "#1A1A1A", c3: "#C8102E", titles: { es: "Invicto en 2010", en: "Unbeaten in 2010" }, facts: { es: ["En 2010 fue el único equipo que terminó invicto el Mundial (3 empates) ¡y quedó afuera!", "Es la gran potencia de Oceanía (OFC).", "Comparte el apodo 'All Whites' como guiño a los All Blacks del rugby."], en: ["In 2010 it was the only unbeaten team (3 draws) — and still went out!", "The dominant power of Oceania (OFC).", "Its 'All Whites' nickname nods to rugby's All Blacks."] } },
  Haiti: { es: "Haití", en: "Haiti", code: "HT", confed: "CONCACAF", nick: { es: "Les Grenadiers", en: "Les Grenadiers" }, c1: "#00209F", c2: "#D21034", c3: "#FFFFFF", titles: { es: "Mundialista 1974", en: "1974 World Cup" }, facts: { es: ["Vuelve a un Mundial tras más de 50 años (su único antecedente fue 1974).", "En 1974, Emmanuel Sanon le cortó un invicto histórico al arquero italiano Zoff.", "Su clasificación fue una alegría enorme en medio de un contexto muy difícil."], en: ["Returns to a World Cup after more than 50 years (its only prior was 1974).", "In 1974, Emmanuel Sanon ended Italy keeper Zoff's record unbeaten run.", "Its qualification brought huge joy amid very hard times."] } },
  Panama: { es: "Panamá", en: "Panama", code: "PA", confed: "CONCACAF", nick: { es: "La Marea Roja", en: "The Red Tide" }, c1: "#DA121A", c2: "#FFFFFF", c3: "#005293", titles: { es: "Fase de grupos 2018", en: "Group stage 2018" }, facts: { es: ["Su debut mundialista fue Rusia 2018, una fiesta nacional total.", "El día que clasificó por primera vez fue declarado feriado nacional.", "Su hinchada tiñe de rojo cada estadio donde juega."], en: ["Its World Cup debut was Russia 2018 — a national party.", "The day it first qualified was declared a national holiday.", "Its fans paint every stadium red."] } },
  "Curaçao": { es: "Curazao", en: "Curaçao", code: "CW", confed: "CONCACAF", nick: { es: "Los Azules", en: "The Blue Wave" }, c1: "#002B7F", c2: "#FFFFFF", c3: "#F9E814", titles: { es: "Debut mundialista", en: "World Cup debut" }, facts: { es: ["Clasifica por PRIMERA vez y es el país más pequeño en llegar a un Mundial (~150 mil hab.).", "Una isla caribeña que escribió una de las páginas más increíbles del fútbol.", "Su clasificación es una de las mayores hazañas de CONCACAF."], en: ["Qualifies for the FIRST time — the smallest nation ever at a World Cup (~150k people).", "A Caribbean island that wrote one of football's most incredible stories.", "Its qualification is one of CONCACAF's greatest feats."] } },
};

// Mapa código ISO -> nombre de equipo (autodetección por país)
const CODE_TO_TEAM = {};
for (const [name, t] of Object.entries(TEAMS)) {
  if (t.code) CODE_TO_TEAM[t.code] = name;
}

// Código para flagcdn (por defecto ISO en minúscula; override con t.fc)
function flagCodeOf(name) {
  const t = TEAMS[name];
  if (!t) return null;
  return (t.fc || (t.code || "").toLowerCase()) || null;
}
